# Generated by Django 3.1.7 on 2021-04-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBerkasProsiding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, unique=True, verbose_name='Judul Jurnal')),
                ('nomor_isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor ISBN')),
                ('tahun_terbit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tahun Terbit')),
                ('penerbit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penerbit')),
                ('url_repository', models.URLField(blank=True, null=True, verbose_name='Link Repository')),
                ('indeks_prosiding', models.CharField(blank=True, max_length=255, null=True, verbose_name='Terindeks di')),
                ('kategori_publikasi', models.CharField(choices=[('Prosiding Forum Ilmiah Internasional', 'Prosiding Forum Ilmiah Internasional'), ('Prosiding Forum Ilmiah Nasional', 'Prosiding Forum Ilmiah Nasional')], default=None, max_length=100, verbose_name='Kategori Publikasi')),
                ('upload_prosiding', models.FileField(upload_to='prosiding/isi/', verbose_name='Upload Prosiding (isi)')),
                ('upload_cover', models.FileField(blank=True, null=True, upload_to='prosiding/cover/', verbose_name='Upload Prosiding (cover)')),
                ('is_verificated', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('corresponding_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_corresponding_author', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding Author')),
                ('pengusul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_pengusul', to=settings.AUTH_USER_MODEL)),
                ('penulis_lain', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('penulis_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_penulis_utama', to=settings.AUTH_USER_MODEL, verbose_name='Penulis Utama')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBerkasJurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, unique=True, verbose_name='Judul Jurnal')),
                ('nomor_issn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor ISSN')),
                ('vol_no_bln_thn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume/No/Bulan/Tahun')),
                ('penerbit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penerbit')),
                ('doi_artikel', models.CharField(blank=True, max_length=255, null=True, verbose_name='DOI Artikel')),
                ('url_jurnal', models.URLField(blank=True, null=True, verbose_name='Link Jurnal')),
                ('indeks_jurnal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indeks Scopus dan Scimagor')),
                ('kategori_publikasi', models.CharField(choices=[('Jurnal Ilmiah Internasional Bereputasi', 'Jurnal Ilmiah Internasional Bereputasi'), ('Jurnal Ilmiah Internasional', 'Jurnal Ilmiah Internasional'), ('Jurnal Ilmiah Nasional Terakreditasi', 'Jurnal Ilmiah Nasional Terakreditasi'), ('Jurnal Ilmiah Nasional Tidak Terakreditasi', 'Jurnal Ilmiah Nasional Tidak Terakreditasi'), ('Jurnal Ilmiah Nasional terindeks di DOAJ dll', 'Jurnal Ilmiah Nasional terindeks di DOAJ dll')], default=None, max_length=100, verbose_name='Kategori Publikasi')),
                ('upload_jurnal', models.FileField(upload_to='jurnal/isi/', verbose_name='Upload Jurnal (isi)')),
                ('upload_cover', models.FileField(blank=True, null=True, upload_to='jurnal/cover/', verbose_name='Upload Jurnal (cover)')),
                ('is_verificated', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('corresponding_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_corresponding_author', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding Author')),
                ('pengusul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_pengusul', to=settings.AUTH_USER_MODEL)),
                ('penulis_lain', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('penulis_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_penulis_utama', to=settings.AUTH_USER_MODEL, verbose_name='Penulis Utama')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBerkasHaki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, unique=True, verbose_name='Nama Berkas')),
                ('kategori_publikasi', models.CharField(choices=[('Internasional (sudah diimplementasikan di industri)', 'Internasional (sudah diimplementasikan di industri)'), ('Internasional', 'Internasional'), ('Nasional (sudah diimplementasikan di industri)', 'Nasional (sudah diimplementasikan di industri)'), ('Nasional', 'Nasional'), ('Nasional (paten dari Dirjen Kekayaan Intelektual)', 'Nasional (paten dari Dirjen Kekayaan Intelektual)'), ('Karya cipta bersertifikat Dirjen', 'Karya cipta bersertifikat Dirjen'), ('Karya cipta bahan ajar', 'Karya cipta bahan ajar')], default=None, max_length=100, verbose_name='Kategori Publikasi')),
                ('upload_berkas', models.FileField(upload_to='jurnal/isi/', verbose_name='Upload Berkas')),
                ('is_verificated', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('pemegang_berkas_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pemegang_berkas_utama', to=settings.AUTH_USER_MODEL, verbose_name='Pemegang Paten Utama')),
                ('pengusul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul', to=settings.AUTH_USER_MODEL)),
                ('penulis_lain', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_haki_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBerkasBuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, unique=True, verbose_name='Judul Buku')),
                ('nomor_isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor ISBN')),
                ('edisi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Edisi')),
                ('tahun_terbit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tahun Terbit')),
                ('penerbit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penerbit')),
                ('jumlah_halaman', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jumlah Halaman')),
                ('kategori_publikasi', models.CharField(choices=[('Buku Referensi', 'Buku Referensi'), ('Buku Monograf', 'Buku Monograf')], default=None, max_length=100, verbose_name='Kategori Publikasi')),
                ('upload_buku', models.FileField(upload_to='buku/isi/', verbose_name='Upload Buku (isi)')),
                ('is_verificated', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('pengusul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_pengusul', to=settings.AUTH_USER_MODEL)),
                ('penulis_lain', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('penulis_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_penulis_utama', to=settings.AUTH_USER_MODEL, verbose_name='Penulis Utama')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
