# Generated by Django 3.1.7 on 2021-04-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0002_auto_20210420_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
