# Generated by Django 3.1.7 on 2021-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0002_auto_20210422_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='tingkat_publikasi',
            field=models.CharField(blank=True, choices=[('Internasional', 'Internasional'), ('Nasional', 'Nasional')], default=None, max_length=100, null=True, verbose_name='Tingkat Publikasi'),
        ),
    ]
