# Generated by Django 3.1.7 on 2021-04-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0003_auto_20210420_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='linieritas',
            field=models.TextField(blank=True, choices=[('Linier dengan bidang kerja', 'Linier dengan bidang kerja'), ('Tidak linier dengan bidang kerja', 'Tidak linier dengan bidang kerja')], null=True, verbose_name='Linieritas'),
        ),
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='plagiasi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Similarity Index'),
        ),
        migrations.DeleteModel(
            name='PlagiasiLinieritas',
        ),
    ]
