# Generated by Django 3.1.7 on 2021-04-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0003_auto_20210424_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='corresponding_author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_corresponding_author', to='penilaian.users', verbose_name='Corresponding Author'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='penulis_utama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_penulis_utama', to='penilaian.users', verbose_name='Penulis Utama'),
        ),
    ]
