# Generated by Django 3.1.7 on 2021-04-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0003_kategoribuku_kategorihaki_kategorijurnal_kategoriprosiding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='kategori_publikasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penilaian.kategoribuku', verbose_name='Kategori Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='kategori_publikasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penilaian.kategorihaki', verbose_name='Kategori Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='kategori_publikasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penilaian.kategorijurnal', verbose_name='Kategori Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='kategori_publikasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penilaian.kategoriprosiding', verbose_name='Kategori Publikasi'),
        ),
    ]
