# Generated by Django 3.1.7 on 2021-04-11 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penilaian', '0003_auto_20210410_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadberkasbuku',
            name='is_verificated',
        ),
        migrations.RemoveField(
            model_name='uploadberkasbuku',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='uploadberkashaki',
            name='is_verificated',
        ),
        migrations.RemoveField(
            model_name='uploadberkashaki',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='uploadberkasjurnal',
            name='is_verificated',
        ),
        migrations.RemoveField(
            model_name='uploadberkasjurnal',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='uploadberkasprosiding',
            name='is_verificated',
        ),
        migrations.RemoveField(
            model_name='uploadberkasprosiding',
            name='reviewer',
        ),
        migrations.CreateModel(
            name='VerifikasiBerkasJurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verificated', models.BooleanField(default=False)),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
