# Generated by Django 3.1.7 on 2021-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0004_auto_20210424_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkashaki',
            name='jenis_haki',
            field=models.CharField(default=None, max_length=50, verbose_name='Jenis HaKI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='nomor_paten',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Paten'),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='penerbit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Penerbit'),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='status_paten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Paten'),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='tanggal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tanggal Berkas'),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='url_repository',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alamat Repository'),
        ),
    ]
