# Generated by Django 3.1.7 on 2021-04-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0004_auto_20210420_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='bukti_plagiasi',
            field=models.FileField(blank=True, null=True, upload_to='plagiasi/', verbose_name='Upload Jurnal (cover)'),
        ),
    ]
