# Generated by Django 3.1.7 on 2021-04-11 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penilaian', '0004_auto_20210411_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='is_verificated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='reviewer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_reviewer', to='auth.user'),
            preserve_default=False,
        ),
    ]
