# Generated by Django 3.1.7 on 2021-04-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0005_auto_20210425_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaianberkasbuku',
            name='jmlh_penulis_lain',
        ),
        migrations.RemoveField(
            model_name='penilaianberkashaki',
            name='jmlh_penulis_lain',
        ),
        migrations.RemoveField(
            model_name='penilaianberkasjurnal',
            name='jmlh_penulis_lain',
        ),
        migrations.RemoveField(
            model_name='penilaianberkasprosiding',
            name='jmlh_penulis_lain',
        ),
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Penulis Selain PU'),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Penulis Selain PU'),
        ),
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Penulis Selain CA dan PU'),
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Penulis Selain CA dan PU'),
        ),
    ]
