# Generated by Django 3.1.7 on 2021-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0005_uploadberkasjurnal_bukti_plagiasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='bukti_plagiasi',
            field=models.FileField(blank=True, null=True, upload_to='plagiasi/', verbose_name='Upload Bukti Plagiasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='indeks_prosiding',
            field=models.CharField(blank=True, choices=[('Scopus dan Scimagojr', 'Scopus dan Scimagojr'), ('Scopus atau IEEE', 'Scopus atau IEEE'), ('Google Scholar', 'Google Scholar'), ('Discontinued dan Cancelled', 'Discontinued dan Cancelled'), ('Tidak Terindeks', 'Tidak Terindeks')], max_length=255, null=True, verbose_name='Terindeks di'),
        ),
    ]
