# Generated by Django 3.1.7 on 2021-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0005_auto_20210429_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoribuku',
            name='informasi_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategoribuku',
            name='pembahasan_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategoribuku',
            name='penerbit_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategoribuku',
            name='unsur_isi_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorihaki',
            name='informasi_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorihaki',
            name='pembahasan_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorihaki',
            name='penerbit_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorihaki',
            name='unsur_isi_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorijurnal',
            name='informasi_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorijurnal',
            name='pembahasan_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorijurnal',
            name='penerbit_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategorijurnal',
            name='unsur_isi_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategoriprosiding',
            name='informasi_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategoriprosiding',
            name='pembahasan_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategoriprosiding',
            name='penerbit_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kategoriprosiding',
            name='unsur_isi_max',
            field=models.FloatField(),
        ),
    ]
