# Generated by Django 3.1.7 on 2021-04-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0006_auto_20210420_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='indeks_jurnal',
            field=models.CharField(blank=True, choices=[('Scopus dan Scimagojr', 'Scopus dan Scimagojr'), ('Scopus atau IEEE', 'Scopus atau IEEE'), ('Google Scholar', 'Google Scholar'), ('Discontinued dan Cancelled', 'Discontinued dan Cancelled'), ('Tidak Terindeks', 'Tidak Terindeks')], max_length=100, null=True, verbose_name='Indeks Jurnal'),
        ),
    ]
