# Generated by Django 3.1.7 on 2021-04-12 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0006_auto_20210411_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianBerkasJurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.PositiveIntegerField(verbose_name='Kelengkapan dan Kesesuaian unsur isi jurnal')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan dan Kesesuaian unsur isi jurnal')),
                ('pembahasan', models.PositiveIntegerField(verbose_name='Ruang lingkup dan kedalaman pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang lingkup dan kedalaman pembahasan')),
                ('informasi', models.TextField(verbose_name='Komentar Kecukupan dan kemutahiran data/informasi dan metodologi')),
                ('kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan unsur dan kualitas penerbit')),
                ('jurnal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal')),
            ],
        ),
        migrations.DeleteModel(
            name='VerifikasiBerkasJurnal',
        ),
    ]
