# Generated by Django 3.1.7 on 2021-04-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0006_auto_20210426_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Penulis Selain PU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='upload_buku',
            field=models.FileField(upload_to='buku/isi/', verbose_name='Upload Buku'),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Penulis Selain PU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='indeks_jurnal',
            field=models.CharField(choices=[('Scopus dan Scimagojr', 'Scopus dan Scimagojr'), ('Scopus atau IEEE', 'Scopus atau IEEE'), ('Google Scholar', 'Google Scholar'), ('Discontinued dan Cancelled', 'Discontinued dan Cancelled'), ('Tidak Terindeks', 'Tidak Terindeks')], default=None, max_length=100, verbose_name='Indeks Jurnal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Penulis Selain CA dan PU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='kategori_publikasi',
            field=models.CharField(choices=[('Jurnal Ilmiah Internasional Bereputasi Berdampak', 'Jurnal Ilmiah Internasional Bereputasi Berdampak'), ('Jurnal Ilmiah Internasional Bereputasi', 'Jurnal Ilmiah Internasional Bereputasi'), ('Jurnal Ilmiah Internasional', 'Jurnal Ilmiah Internasional'), ('Jurnal Ilmiah Nasional Terakreditasi', 'Jurnal Ilmiah Nasional Terakreditasi'), ('Jurnal Ilmiah Nasional Berbahasa PBB', 'Jurnal Ilmiah Nasional Berbahasa PBB'), ('Jurnal Ilmiah Nasional Tidak Terakreditasi', 'Jurnal Ilmiah Nasional Tidak Terakreditasi'), ('Jurnal Ilmiah Nasional terindeks di DOAJ dll', 'Jurnal Ilmiah Nasional terindeks di DOAJ dll')], max_length=100, verbose_name='Kategori Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='indeks_prosiding',
            field=models.CharField(choices=[('Scopus dan Scimagojr', 'Scopus dan Scimagojr'), ('Scopus atau IEEE', 'Scopus atau IEEE'), ('Google Scholar', 'Google Scholar'), ('Discontinued dan Cancelled', 'Discontinued dan Cancelled'), ('Tidak Terindeks', 'Tidak Terindeks')], default=None, max_length=255, verbose_name='Terindeks di'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Penulis Selain CA dan PU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='nomor_isbn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor ISBN'),
        ),
    ]
