# Generated by Django 3.1.7 on 2021-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0007_auto_20210426_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadberkasbuku',
            name='jmlh_penulis_lain',
        ),
        migrations.RemoveField(
            model_name='uploadberkashaki',
            name='jmlh_penulis_lain',
        ),
        migrations.RemoveField(
            model_name='uploadberkasjurnal',
            name='jmlh_penulis_lain',
        ),
        migrations.RemoveField(
            model_name='uploadberkasprosiding',
            name='jmlh_penulis_lain',
        ),
        migrations.AddField(
            model_name='penilaianberkasbuku',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penilaianberkashaki',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penilaianberkasprosiding',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='kategori_publikasi',
            field=models.CharField(choices=[('Jurnal Ilmiah Internasional Bereputasi Berdampak', 'Jurnal Ilmiah Internasional Bereputasi Berdampak'), ('Jurnal Ilmiah Internasional Bereputasi', 'Jurnal Ilmiah Internasional Bereputasi'), ('Jurnal Ilmiah Internasional', 'Jurnal Ilmiah Internasional'), ('Jurnal Ilmiah Nasional Terakreditasi', 'Jurnal Ilmiah Nasional Terakreditasi'), ('Jurnal Ilmiah Nasional Berbahasa PBB', 'Jurnal Ilmiah Nasional Berbahasa PBB'), ('Jurnal Ilmiah Nasional Tidak Terakreditasi', 'Jurnal Ilmiah Nasional Tidak Terakreditasi'), ('Jurnal Ilmiah Nasional terindeks di DOAJ dll', 'Jurnal Ilmiah Nasional terindeks di DOAJ dll')], default=None, max_length=100, verbose_name='Kategori Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='upload_jurnal',
            field=models.FileField(upload_to='jurnal/isi/', verbose_name='Upload Jurnal'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='tingkat_publikasi',
            field=models.CharField(choices=[('Internasional', 'Internasional'), ('Nasional', 'Nasional')], default=None, max_length=100, verbose_name='Tingkat Publikasi'),
        ),
    ]
