# Generated by Django 3.1.7 on 2021-04-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0007_auto_20210412_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='cmnt_informasi',
            field=models.TextField(default=None, verbose_name='Komentar Kecukupan dan kemutahiran data/informasi dan metodologi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='cmnt_kualitas_penerbit',
            field=models.TextField(default=None, verbose_name='Komentar Kelengkapan unsur dan kualitas penerbit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='informasi',
            field=models.PositiveIntegerField(verbose_name='Kecukupan dan kemutahiran data/informasi dan metodologi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='kualitas_penerbit',
            field=models.PositiveIntegerField(verbose_name='Kelengkapan unsur dan kualitas penerbit'),
        ),
    ]
