# Generated by Django 3.1.7 on 2021-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0007_auto_20210420_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='tingkat_jurnal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tingkat Jurnal'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasbuku',
            name='informasi',
            field=models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasbuku',
            name='kualitas_penerbit',
            field=models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasbuku',
            name='pembahasan',
            field=models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasbuku',
            name='unsur_isi',
            field=models.FloatField(verbose_name='Nilai Kelengkapan Unsur Isi Buku'),
        ),
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='informasi',
            field=models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='kualitas_penerbit',
            field=models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit'),
        ),
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='pembahasan',
            field=models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan'),
        ),
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='unsur_isi',
            field=models.FloatField(verbose_name='Nilai Kelengkapan Unsur Isi Deskripsi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='cmnt_informasi',
            field=models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='cmnt_kualitas_penerbit',
            field=models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='cmnt_pembahasan',
            field=models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='cmnt_unsur_isi',
            field=models.TextField(verbose_name='Komentar Kelengkapan dan Kesesuaian Unsur Isi Jurnal'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='informasi',
            field=models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='kualitas_penerbit',
            field=models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='pembahasan',
            field=models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='unsur_isi',
            field=models.FloatField(verbose_name='Nilai Kelengkapan dan Kesesuaian Unsur Isi Jurnal'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='cmnt_informasi',
            field=models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='cmnt_kualitas_penerbit',
            field=models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='cmnt_pembahasan',
            field=models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='informasi',
            field=models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='kualitas_penerbit',
            field=models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='pembahasan',
            field=models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='unsur_isi',
            field=models.FloatField(verbose_name='Nilai Kelengkapan dan Kesesuaian unsur isi prosiding'),
        ),
    ]
