# Generated by Django 3.1.7 on 2021-04-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0008_auto_20210426_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='corresponding_author_selain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_selain', to='penilaian.penulislain', verbose_name='Corresponding Author (selain Dosen)'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='penulis_utama_selain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pu_selain', to='penilaian.penulislain', verbose_name='Penulis Utama (selain Dosen)'),
        ),
    ]
