# Generated by Django 3.1.7 on 2021-04-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0009_auto_20210427_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='reviewer',
            field=models.CharField(max_length=150, verbose_name='Reviewer'),
        ),
    ]
