# Generated by Django 3.1.7 on 2021-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0009_auto_20210503_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='kategori_publikasi',
            field=models.CharField(choices=[('Internasional (sudah diimplementasikan di industri)', 'Internasional (sudah diimplementasikan di industri)'), ('Internasional', 'Internasional'), ('Nasional (sudah diimplementasikan di industri)', 'Nasional (sudah diimplementasikan di industri)'), ('Nasional', 'Nasional'), ('Karya cipta bersertifikat Dirjen', 'Karya cipta bersertifikat Dirjen'), ('Karya cipta bahan ajar', 'Karya cipta bahan ajar')], default=None, max_length=100, verbose_name='Kategori Publikasi'),
        ),
    ]
