# Generated by Django 3.1.7 on 2021-04-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0010_auto_20210412_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='jurnal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal'),
        ),
    ]
