# Generated by Django 3.1.7 on 2021-05-05 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0010_auto_20210503_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_buku', to='penilaian.users', verbose_name='Pengusul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_haki', to='penilaian.users', verbose_name='Pengusul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_jurnal', to='penilaian.users', verbose_name='Pengusul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_prosiding', to='penilaian.users', verbose_name='Pengusul'),
            preserve_default=False,
        ),
    ]
