# Generated by Django 3.1.7 on 2021-05-05 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penilaian', '0011_auto_20210505_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='pengusul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_buku', to=settings.AUTH_USER_MODEL, verbose_name='Pengusul'),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='pengusul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_haki', to=settings.AUTH_USER_MODEL, verbose_name='Pengusul'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='pengusul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_jurnal', to=settings.AUTH_USER_MODEL, verbose_name='Pengusul'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='pengusul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul_prosiding', to=settings.AUTH_USER_MODEL, verbose_name='Pengusul'),
        ),
    ]
