# Generated by Django 3.1.7 on 2021-04-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0011_auto_20210412_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Nilai'),
        ),
    ]
