# Generated by Django 3.1.7 on 2021-04-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0012_penilaianberkasjurnal_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='jurnal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal'),
        ),
    ]
