# Generated by Django 3.1.7 on 2021-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0012_auto_20210505_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
