# Generated by Django 3.1.7 on 2021-05-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0013_auto_20210505_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianberkasbuku',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
