# Generated by Django 3.1.7 on 2021-05-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0014_auto_20210505_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_reviewer2', to='penilaian.reviewer'),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_haki_reviewer2', to='penilaian.reviewer'),
        ),
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_reviewer2', to='penilaian.reviewer'),
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_reviewer2', to='penilaian.reviewer'),
        ),
    ]
