# Generated by Django 3.1.7 on 2021-04-12 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0015_uploadberkasjurnal_jmlh_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='nilai_ca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Corresponding Author'),
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='nilai_pl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Penulis Lainnya'),
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='nilai_pu',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Penulis Utama'),
        ),
    ]
