# Generated by Django 3.1.7 on 2021-04-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0016_auto_20210412_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='nip',
            field=models.CharField(default=None, max_length=18, verbose_name='Nomor Induk Pegawai'),
        ),
    ]
