# Generated by Django 3.1.7 on 2021-05-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0016_auto_20210505_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaianberkasbuku',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='penilaianberkashaki',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='penilaianberkasjurnal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='penilaianberkasprosiding',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='uploadberkasbuku',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='uploadberkashaki',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='uploadberkasjurnal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='uploadberkasprosiding',
            name='slug',
        ),
        migrations.CreateModel(
            name='PenilaianBerkasJurnal2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.FloatField(verbose_name='Nilai Kelengkapan dan Kesesuaian Unsur Isi Jurnal')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan dan Kesesuaian Unsur Isi Jurnal')),
                ('pembahasan', models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan')),
                ('informasi', models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('cmnt_informasi', models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('kualitas_penerbit', models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit')),
                ('cmnt_kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total Nilai')),
                ('nilai_ca', models.FloatField(blank=True, null=True, verbose_name='Nilai Corresponding Author')),
                ('nilai_pu', models.FloatField(blank=True, null=True, verbose_name='Nilai Penulis Utama')),
                ('nilai_pl', models.FloatField(blank=True, null=True, verbose_name='Nilai Penulis Lainnya')),
                ('jmlh_penulis_lain', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jurnal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal')),
            ],
        ),
    ]
