# Generated by Django 3.1.7 on 2021-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0017_reviewer_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=None, verbose_name='Jumlah Penulis (selain CA dan PU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='upload_berkas',
            field=models.FileField(upload_to='haki/isi/', verbose_name='Upload Berkas'),
        ),
    ]
