# Generated by Django 3.1.7 on 2021-05-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0017_auto_20210507_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianBerkasProsiding2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.FloatField(verbose_name='Nilai Kelengkapan dan Kesesuaian unsur isi prosiding')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan dan Kesesuaian unsur isi prosiding')),
                ('pembahasan', models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan')),
                ('informasi', models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('cmnt_informasi', models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('kualitas_penerbit', models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit')),
                ('cmnt_kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total Nilai')),
                ('nilai_ca', models.FloatField(blank=True, null=True, verbose_name='Nilai Corresponding Author')),
                ('nilai_pu', models.FloatField(blank=True, null=True, verbose_name='Nilai Penulis Utama')),
                ('nilai_pl', models.FloatField(blank=True, null=True, verbose_name='Nilai Penulis Lainnya')),
                ('jmlh_penulis_lain', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prosiding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasprosiding')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianBerkasHaki2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.FloatField(verbose_name='Nilai Kelengkapan Unsur Isi Deskripsi')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan Unsur Isi Deskripsi')),
                ('pembahasan', models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan')),
                ('informasi', models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('cmnt_informasi', models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('kualitas_penerbit', models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit')),
                ('cmnt_kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total Nilai')),
                ('nilai_pu', models.FloatField(blank=True, null=True, verbose_name='Nilai Pemegang Berkas Utama')),
                ('nilai_pl', models.FloatField(blank=True, null=True, verbose_name='Nilai Pemegang Berkas Lainnya')),
                ('jmlh_penulis_lain', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('berkas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkashaki')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianBerkasBuku2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.FloatField(verbose_name='Nilai Kelengkapan Unsur Isi Buku')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan Unsur Isi Buku')),
                ('pembahasan', models.FloatField(verbose_name='Nilai Ruang Lingkup dan Kedalaman Pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan')),
                ('informasi', models.FloatField(verbose_name='Nilai Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('cmnt_informasi', models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('kualitas_penerbit', models.FloatField(verbose_name='Nilai Kelengkapan Unsur dan Kualitas Penerbit')),
                ('cmnt_kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total Nilai')),
                ('nilai_pu', models.FloatField(blank=True, null=True, verbose_name='Nilai Penulis Utama')),
                ('nilai_pl', models.FloatField(blank=True, null=True, verbose_name='Nilai Penulis Lainnya')),
                ('jmlh_penulis_lain', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasbuku')),
            ],
        ),
    ]
