# Generated by Django 3.1.7 on 2021-04-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0018_auto_20210413_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='jmlh_penulis',
            field=models.PositiveIntegerField(default=None, verbose_name='Jumlah Penulis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=None, verbose_name='Jumlah Penulis (selain penulis utama)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_reviewer', to='penilaian.reviewer'),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='jmlh_penulis',
            field=models.PositiveIntegerField(default=None, verbose_name='Jumlah Pemegang Berkas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=None, verbose_name='Jumlah Pemegang Berkas Lain (selain pemegang berkas utama)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_haki_reviewer', to='penilaian.reviewer'),
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='jmlh_penulis',
            field=models.PositiveIntegerField(default=None, verbose_name='Jumlah Penulis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(default=None, verbose_name='Jumlah Penulis (selain CA dan PU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_reviewer', to='penilaian.reviewer'),
        ),
        migrations.CreateModel(
            name='PenilaianBerkasProsiding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.PositiveIntegerField(verbose_name='Kelengkapan dan Kesesuaian unsur isi prosiding')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan dan Kesesuaian unsur isi prosiding')),
                ('pembahasan', models.PositiveIntegerField(verbose_name='Ruang lingkup dan kedalaman pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang lingkup dan kedalaman pembahasan')),
                ('informasi', models.PositiveIntegerField(verbose_name='Kecukupan dan kemutahiran data/informasi dan metodologi')),
                ('cmnt_informasi', models.TextField(verbose_name='Komentar Kecukupan dan kemutahiran data/informasi dan metodologi')),
                ('kualitas_penerbit', models.PositiveIntegerField(verbose_name='Kelengkapan unsur dan kualitas penerbit')),
                ('cmnt_kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan unsur dan kualitas penerbit')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Nilai')),
                ('nilai_ca', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Corresponding Author')),
                ('nilai_pu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Penulis Utama')),
                ('nilai_pl', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Penulis Lainnya')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('prosiding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianBerkasHaki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.PositiveIntegerField(verbose_name='Kelengkapan Unsur Isi Buku')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan Unsur Isi Buku')),
                ('pembahasan', models.PositiveIntegerField(verbose_name='Ruang Lingkup dan Kedalaman Pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan')),
                ('informasi', models.PositiveIntegerField(verbose_name='Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('cmnt_informasi', models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('kualitas_penerbit', models.PositiveIntegerField(verbose_name='Kelengkapan Unsur dan Kualitas Penerbit')),
                ('cmnt_kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Nilai')),
                ('nilai_pu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Pemegang Berkas Utama')),
                ('nilai_pl', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Pemegang Berkas Lainnya')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('berkas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianBerkasBuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur_isi', models.PositiveIntegerField(verbose_name='Kelengkapan Unsur Isi Buku')),
                ('cmnt_unsur_isi', models.TextField(verbose_name='Komentar Kelengkapan Unsur Isi Buku')),
                ('pembahasan', models.PositiveIntegerField(verbose_name='Ruang Lingkup dan Kedalaman Pembahasan')),
                ('cmnt_pembahasan', models.TextField(verbose_name='Komentar Ruang Lingkup dan Kedalaman Pembahasan')),
                ('informasi', models.PositiveIntegerField(verbose_name='Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('cmnt_informasi', models.TextField(verbose_name='Komentar Kecukupan dan Kemutahiran Data/Informasi dan Metodologi')),
                ('kualitas_penerbit', models.PositiveIntegerField(verbose_name='Kelengkapan Unsur dan Kualitas Penerbit')),
                ('cmnt_kualitas_penerbit', models.TextField(verbose_name='Komentar Kelengkapan Unsur dan Kualitas Penerbit')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Nilai')),
                ('nilai_pu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Penulis Utama')),
                ('nilai_pl', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Penulis Lainnya')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('buku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasjurnal')),
            ],
        ),
    ]
