# Generated by Django 3.1.7 on 2021-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0018_penilaianberkasbuku2_penilaianberkashaki2_penilaianberkasprosiding2'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal2',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
