# Generated by Django 3.1.7 on 2021-04-14 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0019_auto_20210413_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianberkasbuku',
            name='buku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasbuku'),
        ),
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='berkas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkashaki'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='prosiding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.uploadberkasprosiding'),
        ),
    ]
