# Generated by Django 3.1.7 on 2021-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0020_auto_20210508_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='uploadberkashaki',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
