# Generated by Django 3.1.7 on 2021-04-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0020_auto_20210414_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiasiLinieritas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plagiasi', models.TextField(verbose_name='Komentar Plagiasi')),
                ('linieritas', models.TextField(verbose_name='Komentar Linieritas')),
                ('jurnal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiasi_linieritas', to='penilaian.uploadberkasjurnal')),
            ],
        ),
    ]
