# Generated by Django 3.1.7 on 2021-04-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penilaian', '0022_auto_20210414_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='linieritas',
            field=models.TextField(default=None, verbose_name='Komentar Linieritas Jurnal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='plagiasi',
            field=models.TextField(default=None, verbose_name='Komentar Plagiasi Jurnal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlagiasiLinieritas',
        ),
    ]
