# Generated by Django 3.1.7 on 2021-05-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0022_auto_20210509_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='penulis_utama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_penulis_utama', to='penilaian.users', verbose_name='Penulis Utama'),
        ),
    ]
