# Generated by Django 3.1.7 on 2021-05-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0023_auto_20210509_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='linieritas',
            field=models.TextField(blank=True, choices=[('Linier dengan bidang penulis', 'Linier dengan bidang penulis'), ('Tidak linier dengan bidang penulis', 'Tidak linier dengan bidang penulis')], null=True, verbose_name='Linieritas'),
        ),
    ]
