# Generated by Django 3.1.7 on 2021-04-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0023_auto_20210414_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaianberkasjurnal',
            name='linieritas',
        ),
        migrations.RemoveField(
            model_name='penilaianberkasjurnal',
            name='plagiasi',
        ),
        migrations.CreateModel(
            name='PlagiasiLinieritas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plagiasi', models.TextField(verbose_name='Komentar Plagiasi')),
                ('linieritas', models.TextField(verbose_name='Komentar Linieritas')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('jurnal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiasi_linieritas', to='penilaian.uploadberkasjurnal')),
            ],
        ),
    ]
