# Generated by Django 3.1.7 on 2021-06-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0024_auto_20210528_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='ttd',
            field=models.FileField(blank=True, default=None, upload_to='ttd/', verbose_name='Upload Tanda Tangan'),
        ),
    ]
