# Generated by Django 3.1.7 on 2021-06-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0025_reviewer_ttd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='ttd',
            field=models.ImageField(blank=True, default=None, upload_to='ttd/', verbose_name='Upload Tanda Tangan'),
        ),
    ]
