# Generated by Django 3.1.7 on 2021-04-15 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penilaian', '0025_auto_20210415_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='reviewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_pengusul', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='penulis_utama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_penulis_utama', to=settings.AUTH_USER_MODEL, verbose_name='Penulis Utama'),
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='reviewer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_buku_reviewer', to='penilaian.reviewer'),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='pemegang_berkas_utama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pemegang_berkas_utama', to=settings.AUTH_USER_MODEL, verbose_name='Pemegang Paten Utama'),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pengusul', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='reviewer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_haki_reviewer', to='penilaian.reviewer'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='corresponding_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_corresponding_author', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding Author'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_pengusul', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='penulis_utama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_penulis_utama', to=settings.AUTH_USER_MODEL, verbose_name='Penulis Utama'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='reviewer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_jurnal_reviewer', to='penilaian.reviewer'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='corresponding_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_corresponding_author', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding Author'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='pengusul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_pengusul', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='penulis_utama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_penulis_utama', to=settings.AUTH_USER_MODEL, verbose_name='Penulis Utama'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='reviewer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prosiding_reviewer', to='penilaian.reviewer'),
        ),
    ]
