# Generated by Django 3.1.7 on 2021-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0026_auto_20210415_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='cmnt_unsur_isi',
            field=models.TextField(verbose_name='Komentar Kelengkapan Unsur Isi Deskripsi'),
        ),
        migrations.AlterField(
            model_name='penilaianberkashaki',
            name='unsur_isi',
            field=models.PositiveIntegerField(verbose_name='Kelengkapan Unsur Isi Deskripsi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Penulis (selain penulis utama)'),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Pemegang Berkas Lain (selain pemegang berkas utama)'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Penulis (selain CA dan PU)'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Penulis (selain CA dan PU)'),
        ),
    ]
