# Generated by Django 3.1.7 on 2021-06-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0026_auto_20210609_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='jabatan',
            field=models.CharField(default=None, max_length=70, verbose_name='Jabatan Fungsional'),
        ),
        migrations.AddField(
            model_name='users',
            name='pangkat',
            field=models.CharField(default=None, max_length=70, verbose_name='Pangkat/Golongan/Ruang'),
        ),
        migrations.AddField(
            model_name='users',
            name='unit',
            field=models.CharField(default=None, max_length=100, verbose_name='Unit Kerja'),
        ),
    ]
