# Generated by Django 3.1.7 on 2021-06-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0027_auto_20210611_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='GabunganPenilaianBerkasJurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_total_pu', models.FloatField(verbose_name='Nilai Total Penulis Utama')),
                ('nilai_total_ca', models.FloatField(verbose_name='Nilai Total Penulis Korespondensi')),
                ('nilai_total_pl', models.FloatField(verbose_name='Nilai Total Penulis Lainnya')),
                ('nilai_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.penilaianberkasjurnal')),
                ('nilai_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penilaian.penilaianberkasjurnal2')),
            ],
        ),
    ]
