# Generated by Django 3.1.7 on 2021-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0027_auto_20210416_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='judul',
            field=models.CharField(max_length=255, verbose_name='Judul Buku'),
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='nomor_isbn',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Nomor ISBN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='judul',
            field=models.CharField(max_length=255, verbose_name='Judul Jurnal'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='nomor_issn',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Nomor ISSN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='judul',
            field=models.CharField(max_length=255, verbose_name='Judul Jurnal'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='nomor_isbn',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Nomor ISBN'),
            preserve_default=False,
        ),
    ]
