# Generated by Django 3.1.7 on 2021-04-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0028_auto_20210416_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='tingkat_publikasi',
            field=models.CharField(blank=True, choices=[('Internasional Terindeks Scimagor & Scopus', 'Internasional Terindeks Scimagor & Scopus'), ('Internasional Terindeks Scopus / IEEE', 'Internasional Terindeks Scopus / IEEE'), ('Internasional', 'Internasional'), ('Nasional', 'Nasional')], default=None, max_length=100, null=True, verbose_name='Tingkat Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasbuku',
            name='kategori_publikasi',
            field=models.CharField(choices=[('Buku Referensi', 'Buku Referensi'), ('Buku Monograf', 'Buku Monograf'), ('Book Chapter Internasional', 'Book Chapter Internasional'), ('Book Chapter Nasional', 'Book Chapter Nasional')], default=None, max_length=100, verbose_name='Kategori Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='kategori_publikasi',
            field=models.CharField(choices=[('Jurnal Ilmiah Internasional Bereputasi Berdampak', 'Jurnal Ilmiah Internasional Bereputasi Berdampak'), ('Jurnal Ilmiah Internasional Bereputasi', 'Jurnal Ilmiah Internasional Bereputasi'), ('Jurnal Ilmiah Internasional', 'Jurnal Ilmiah Internasional'), ('Jurnal Ilmiah Nasional Terakreditasi', 'Jurnal Ilmiah Nasional Terakreditasi'), ('Jurnal Ilmiah Nasional Berbahasa PBB', 'Jurnal Ilmiah Nasional Berbahasa PBB'), ('Jurnal Ilmiah Nasional Tidak Terakreditasi', 'Jurnal Ilmiah Nasional Tidak Terakreditasi'), ('Jurnal Ilmiah Nasional terindeks di DOAJ dll', 'Jurnal Ilmiah Nasional terindeks di DOAJ dll')], default=None, max_length=100, verbose_name='Kategori Publikasi'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='kategori_publikasi',
            field=models.CharField(choices=[('Presentasi Oral dan Dipublikasikan', 'Presentasi Oral dan Dipublikasikan'), ('Poster dan Dipublikasikan dalam Prosiding', 'Poster dan Dipublikasikan dalam Prosiding'), ('Diseminarkan Namun Tidak Terpublikasi', 'Diseminarkan Namun Tidak Terpublikasi'), ('Tidak Diseminarkan Namun Terpublikasi', 'Tidak Diseminarkan Namun Terpublikasi'), ('Terpublikasi dalam Koran/Majalah', 'Terpublikasi dalam Koran/Majalah')], default=None, max_length=100, verbose_name='Kategori Publikasi'),
        ),
    ]
