# Generated by Django 3.1.7 on 2021-04-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0029_auto_20210416_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='url_jurnal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Link Jurnal'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='url_repository',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Link Repository'),
        ),
    ]
