# Generated by Django 3.1.7 on 2021-04-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0030_auto_20210417_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadberkasbuku',
            name='pengusul',
        ),
        migrations.RemoveField(
            model_name='uploadberkashaki',
            name='pengusul',
        ),
        migrations.RemoveField(
            model_name='uploadberkasjurnal',
            name='pengusul',
        ),
        migrations.RemoveField(
            model_name='uploadberkasprosiding',
            name='pengusul',
        ),
    ]
