# Generated by Django 3.1.7 on 2021-06-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0030_auto_20210614_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='linieritas',
            field=models.CharField(default=None, max_length=150, verbose_name='Komentar Linieritas dari Reviewer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='plagiasi',
            field=models.CharField(default=None, max_length=150, verbose_name='Komentar Plagiasi dari Reviewer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal2',
            name='linieritas',
            field=models.CharField(default=None, max_length=150, verbose_name='Komentar Linieritas dari Reviewer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal2',
            name='plagiasi',
            field=models.CharField(default=None, max_length=150, verbose_name='Komentar Plagiasi dari Reviewer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasprosiding',
            name='plagiasi',
            field=models.CharField(default=None, max_length=150, verbose_name='Komentar Plagiasi dari Reviewer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianberkasprosiding2',
            name='plagiasi',
            field=models.CharField(default=None, max_length=150, verbose_name='Komentar Plagiasi dari Reviewer'),
            preserve_default=False,
        ),
    ]
