# Generated by Django 3.1.7 on 2021-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0031_auto_20210614_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='linieritas',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Komentar Linieritas dari Reviewer'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal',
            name='plagiasi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Komentar Plagiasi dari Reviewer'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal2',
            name='linieritas',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Komentar Linieritas dari Reviewer'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasjurnal2',
            name='plagiasi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Komentar Plagiasi dari Reviewer'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding',
            name='plagiasi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Komentar Plagiasi dari Reviewer'),
        ),
        migrations.AlterField(
            model_name='penilaianberkasprosiding2',
            name='plagiasi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Komentar Plagiasi dari Reviewer'),
        ),
    ]
