# Generated by Django 3.1.7 on 2021-04-19 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penilaian', '0031_auto_20210419_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadberkasjurnal',
            name='jmlh_penulis_lain',
        ),
        migrations.AddField(
            model_name='penilaianberkasjurnal',
            name='jmlh_penulis_lain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadberkashaki',
            name='pemegang_berkas_utama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pemegang_berkas_utama', to=settings.AUTH_USER_MODEL, verbose_name='Pemegang Berkas Utama'),
        ),
    ]
