# Generated by Django 3.1.7 on 2021-06-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0033_auto_20210621_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasbuku',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume'),
        ),
    ]
