# Generated by Django 3.1.7 on 2021-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0036_auto_20210930_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadberkasjurnal',
            name='upload_jurnal',
            field=models.FileField(blank=True, null=True, upload_to='jurnal/isi/', verbose_name='Upload Jurnal'),
        ),
        migrations.AlterField(
            model_name='uploadberkasprosiding',
            name='upload_prosiding',
            field=models.FileField(blank=True, null=True, upload_to='prosiding/isi/', verbose_name='Upload Prosiding (isi)'),
        ),
    ]
