# Generated by Django 3.1.7 on 2022-05-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0038_auto_20220509_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkasjurnal',
            name='url_pengindeks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Pengindeks'),
        ),
        migrations.AddField(
            model_name='uploadberkasprosiding',
            name='url_pengindeks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Pengindeks'),
        ),
    ]
