# Generated by Django 3.1.7 on 2022-05-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0040_uploadberkasprosiding_doi_artikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadberkashaki',
            name='url_penerbit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Penerbit Sertifikat'),
        ),
    ]
